# Generated by Django 2.0.5 on 2018-06-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypathoapp', '0003_auto_20180603_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccpr',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
