# Generated by Django 2.0.5 on 2018-06-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypathoapp', '0004_ccpr_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='sin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Repeatpassword', models.CharField(max_length=20)),
            ],
        ),
    ]
