# Generated by Django 2.0.5 on 2018-06-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypathoapp', '0005_sin_sup'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pack', models.CharField(max_length=20, null=True)),
                ('service', models.CharField(max_length=20, null=True)),
                ('test', models.CharField(max_length=20, null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('std', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('month', models.CharField(max_length=10)),
                ('day', models.IntegerField()),
                ('year', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='sin',
        ),
        migrations.RemoveField(
            model_name='sup',
            name='Repeatpassword',
        ),
        migrations.AlterField(
            model_name='ccpr',
            name='phone',
            field=models.IntegerField(default=False),
        ),
    ]
