# Generated by Django 2.0.5 on 2018-06-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypathoapp', '0006_auto_20180607_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
