# Generated by Django 2.0.5 on 2018-06-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypathoapp', '0007_auto_20180607_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
